name: DeepDicomSort_MONAI
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blinker=1.6.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - comm=0.1.4
  - cryptography=41.0.3
  - dcm2niix=1.0.20230411
  - debugpy=1.6.8
  - decorator=5.1.1
  - dicom2nifti=2.4.8
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.12.2
  - flatbuffers=23.5.26
  - frozenlist=1.4.0
  - gast=0.4.0
  - gdcm=2.8.9
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - grpcio=1.54.3
  - h5py=3.9.0
  - hdf5=1.14.2
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.1
  - ipython=8.14.0
  - jax=0.4.14
  - jaxlib=0.4.14
  - jedi=0.19.0
  - jinja2=3.1.2
  - json-c=0.16
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.0.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgrpc=1.54.3
  - libhwloc=2.9.2
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.44.2
  - libwebp-base=1.3.1
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - ml_dtypes=0.2.0
  - monai=1.2.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nibabel=5.1.0
  - numpy=1.25.2
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.0.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.5.1
  - pooch=1.7.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.21.12
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydicom=2.4.3
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python-wget=3.2
  - python_abi=3.11
  - pytorch=2.0.0
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2023.03.02
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rocm-smi=5.6.0
  - rsa=4.9
  - scipy=1.11.2
  - setuptools=68.1.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.10.0
  - tensorboard=2.12.3
  - tensorboard-data-server=0.7.0
  - tensorflow=2.12.1
  - tensorflow-base=2.12.1
  - tensorflow-estimator=2.12.1
  - termcolor=2.3.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - werkzeug=2.3.7
  - wget=1.20.3
  - wheel=0.41.2
  - wrapt=1.15.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.2
